### ISSUE TITLE
Issue with node-6.3.0, Rapsberry pi

### ISSUE THREAD

**Issue by navaneetharaopy** [http-auth/apache-crypt#10]
`OS: Raspbian jessie`
`Board: Raspberry pi 3`
`node : node v6.3.0`

while installing apache-crypt  using command `npm install apache-crypt`received following error. 

./node_modules/nan/nan.h:1994:23: error: 'ExternalAsciiStringResource' in 'class v8::String' does not name a type
     const v8::String::ExternalAsciiStringResource* ext;
                       ^
../node_modules/nan/nan.h:1995:5: error: 'ext' was not declared in this scope
     ext = str->GetExternalAsciiStringResource();
     ^
../node_modules/nan/nan.h:1995:16: error: 'class v8::String' has no member named 'GetExternalAsciiStringResource'
     ext = str->GetExternalAsciiStringResource();
                ^

gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/opt/node/armv7l/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Linux 4.4.22-v7+
gyp ERR! command "/opt/node/armv7l/bin/node" "/opt/node/armv7l/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/pi/proj/node_modules/apache-crypt
gyp ERR! node -v v6.3.0
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok 
     npm WARN install:apache-crypt@1.0.6 apache-crypt@1.0.6 install: `node-gyp rebuild`
     npm WARN install:apache-crypt@1.0.6 Exit status 1

**Comment by gevorg** [comment]
Current apache-crypt version is apache-crypt@1.1.2, please try with that version, not sure why do you use old version.
